version: '3.2'
services:
  cadvisor:
    image: google/cadvisor
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - "/:/rootfs:ro"
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

